version: "3"

env:
  SDL_LOGGING: "*=debug"

dotenv:
  - .env

tasks:
  build:linux:
    desc: Build the project with Linux
    cmds:
      - cmake -S . -B "build" -G "$GENERATOR" -DCMAKE_TOOLCHAIN_FILE="$VCPKG_TOOLCHAIN_FILE" -DCMAKE_CXX_COMPILER="$CMAKE_CXX_COMPILER" -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON
      - cmake --build "build" --config Debug -j
      - ctest --test-dir "build" --output-on-failure

  run:linux:
    desc: Run the project with Linux
    env:
      LSAN_OPTIONS: "suppressions=lsansupp"
    cmds:
      - ./build/bin/CCSakura
