# This is a tool-file, meant to transform the provided sprite and
# json file into a .sprite file (generated by Aseprite).

from io import BufferedWriter
import sys
import os
import json
import struct
import logging
import colorlog


TOOL_VERSION = 1


formatter = colorlog.ColoredFormatter(
    "%(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s",
    log_colors={
        "DEBUG": "cyan",
        "INFO": "green",
        "WARNING": "yellow",
        "ERROR": "red",
        "CRITICAL": "red",
    },
    secondary_log_colors={"message": {"ERROR": "red", "CRITICAL": "red"}},
)

# Get the root logger
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)

# Create a console handler
handler = logging.StreamHandler()
handler.setFormatter(formatter)

# Add the handler to the logger
logger.addHandler(handler)


def write_frame_tags(f: BufferedWriter, tags: list[dict]):
    for tag in tags:
        # Length of the name (u32), the name (char*), and from (u32) frame what to frame what (u32)
        f.write(struct.pack("<I", len(tag["name"])))
        f.write(struct.pack(f"<{len(tag['name'])}s", bytes(tag["name"], "utf-8")))
        f.write(struct.pack("<I", tag["from"]))
        f.write(struct.pack("<I", tag["to"]))


def write_frames(f: BufferedWriter, frames: list[dict]):
    for frame in frames:
        # Source size, relative source size, absolute source rect
        f.write(struct.pack("<I", frame["sourceSize"]["w"]))
        f.write(struct.pack("<I", frame["sourceSize"]["h"]))
        f.write(struct.pack("<I", frame["spriteSourceSize"]["x"]))
        f.write(struct.pack("<I", frame["spriteSourceSize"]["y"]))
        f.write(struct.pack("<I", frame["spriteSourceSize"]["w"]))
        f.write(struct.pack("<I", frame["spriteSourceSize"]["h"]))
        f.write(struct.pack("<I", frame["frame"]["x"]))
        f.write(struct.pack("<I", frame["frame"]["y"]))
        f.write(struct.pack("<I", frame["frame"]["w"]))
        f.write(struct.pack("<I", frame["frame"]["h"]))
        f.write(struct.pack("<I", frame["duration"]))


def write_sprite(sprsheet: str, outpath: str, data: dict):
    with open(outpath, "wb") as f:
        logger.info(f"Using sprite to binary tool v{TOOL_VERSION}")
        f.write(struct.pack("<I", TOOL_VERSION))

        f.write(struct.pack("<Q", os.path.getsize(sprsheet)))
        logger.info(f"Written {os.path.getsize(sprsheet)} bytes as image length")

        with open(sprsheet, "rb") as img:
            f.write(img.read())  # Needs work if sprite sheet is giant.
        logger.info("Written all of image data")

        w = data["meta"]["size"]["w"]
        h = data["meta"]["size"]["h"]
        logger.info(f"Writing image dimensions {w}x{h}")
        f.write(struct.pack("<I", w))
        f.write(struct.pack("<I", h))

        logger.debug("Writing frame tags data")
        frame_tags = data["meta"]["frameTags"]
        f.write(struct.pack("<I", len(frame_tags)))
        logger.info(f"Starting to write {len(frame_tags)} frame tags")

        write_frame_tags(f, frame_tags)

        logger.debug("Writing frames data")
        frames = data["frames"]
        f.write(struct.pack("<I", len(frames)))
        logger.info(f"Starting to write {len(frames)} frames")

        write_frames(f, frames)


def main():
    if len(sys.argv) < 3:
        logger.fatal("This script requires 2 arguments.")
        return

    if len(sys.argv) > 3:
        logger.warning(
            f"There are more arguments than required, ignoring: {sys.argv[3:]}"
        )

    sprsheet = sys.argv[1]
    sprdata = sys.argv[2]
    logger.info(f"Sprite sheet is selected to be {sprsheet}")
    logger.info(f"Sprite data is selected to be {sprdata}")

    try:
        with open(sprdata, "r") as f:
            logger.debug("Reading sprite data JSON")
            data = json.load(f)
            logger.info(f"Read sprite data JSON as {str(data)[:16]}...")

        # Open a new file for writing at the same path of the provided sheet
        sprname, _ = os.path.splitext(sprsheet)
        outpath = f"{sprname}.sprite"
        logger.debug(f"Using out file at path {outpath}")
        write_sprite(sprsheet, outpath, data)

    except OSError:
        print("An error occurred while opening those files")


if __name__ == "__main__":
    main()
