name: Build & Test

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout with Submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for version tagging

      - name: Cache vcpkg
        uses: actions/cache@v4
        id: vcpkg-cache
        with:
          path: |
            ${{ github.workspace }}/vcpkg
            ${{ github.workspace }}/build/vcpkg_installed
          key: ${{ runner.os }}-${{ hashFiles('./vcpkg.json') }}

      - name: Setup vcpkg (Unix)
        if: steps.vcpkg-cache.outputs.cache-hit != 'true' && matrix.os != 'windows-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg ./vcpkg
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Setup vcpkg (Windows)
        if: steps.vcpkg-cache.outputs.cache-hit != 'true' && matrix.os == 'windows-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg ./vcpkg
          ./vcpkg/bootstrap-vcpkg.bat

      - name: Build with CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake" -DBUILD_TESTING=ON
          cmake --build build --config Release -j

      - name: Test with CTest
        run: |
          ctest -C Release --test-dir build --output-on-failure

      - name: Final steps
        run: |
          ls -R build

      - name: Package artifacts (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p CCSakura-Linux
          mv -v build/bin/* CCSakura-Linux
          cp -R -v assets CCSakura-Linux

      - name: Package artifacts (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          mv build/bin/CCSakura.app CCSakura.app
          mkdir -p CCSakura.app/Contents/Resources
          cp -R -v assets CCSakura.app/Contents/Resources

      - name: Package artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p CCSakura-Win
          mv -Verbose "build\bin\Release\*" "CCSakura-Win"
          cp -Path assets -Destination "CCSakura-Win\assets" -Recurse -Verbose

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CCSakura-${{ runner.os }}
          path: |
            ./CCSakura-Win/
            ./CCSakura.app/
            ./CCSakura-Linux/
          retention-days: 30
